"""
AI Use Case Context Framework
==============================
A generalizable governance model for AI-driven media production use cases.

Provides flag, route, and block capabilities across six core risk dimensions:
  - Legal / IP Ownership
  - Bias / Fairness
  - Safety / Harmful Output
  - Security / Model Integrity
  - Technical Feasibility
  - Output Quality

Plus configurable security dimensions aligned with industry standards:
  - **TPN** (Trusted Partner Network / MPA Content Security)
  - **VFX platform** security best practices
  - **Enterprise InfoSec** controls (ISO 27001, SOC 2, NIST-aligned)

And an open governance hook protocol for enterprise integrations:
  - Audit logging, compliance gates, notification bridges
  - Custom hook classes for SIEM, ticketing, and policy enforcement

Designed to integrate with PRD and taxonomy frameworks, including
MovieLabs OMC-aligned production workflows.
"""

from ai_use_case_context.authority import (
    Authority,
    AuthoritySource,
    SUGGESTED_CLEARANCE_ROLE,
    suggested_clearance_role,
    TermDefinition,
    TermConflict,
    Lexicon,
    default_lexicon,
)
from ai_use_case_context.core import (
    RiskDimension,
    RiskLevel,
    ReviewStatus,
    RiskFlag,
    UseCaseContext,
    Dimension,
    DimensionType,
    custom_dimension,
    DEFAULT_ROUTING,
)
from ai_use_case_context.vocabulary import (
    VocabularyMapping,
    register_vocabulary,
    unregister_vocabulary,
    get_vocabulary,
    list_vocabularies,
)
from ai_use_case_context.capability import (
    TransformationClass,
    ControlMode,
    FinalPixelRole,
    LikenessPresence,
    RegionProfile,
    CapabilityRule,
    CapabilityProfile,
    DEFAULT_CAPABILITY_RULES,
)
from ai_use_case_context.pipeline_signals import (
    OutputComposition,
    DerivationThresholds,
    DEFAULT_THRESHOLDS,
    GuidanceSignal,
    PipelineRecord,
    derive_transformation,
    derive_control_mode,
    derive_final_pixel_role,
    derive_region_profile,
)
from ai_use_case_context.intake import (
    ProjectVisibility,
    IPClass,
    RESTRICTED_IP_CLASSES,
    CommercialNature,
    UseCaseMaturity,
    PrimaryUser,
    BusinessContext,
    ApprovalSubject,
    ApprovalDecision,
    ApprovalContext,
    InputType,
    OutputRole,
    BrandPresence,
    InputProfile,
    OutputProfile,
    IntakeRule,
    UseCaseProfile,
    DEFAULT_INTAKE_RULES,
)
from ai_use_case_context.operations import (
    HostEnvironment,
    UpdateControl,
    Deployment,
    Custodian,
    DataResidency,
    CollectionPolicy,
    INDEFINITE_RETENTION,
    DataCollection,
    RefinementLocation,
    ModelRefinement,
    OperationalRule,
    OperationalProfile,
    DEFAULT_OPERATIONAL_RULES,
)
from ai_use_case_context.authorship import (
    AuthorshipEvidence,
    AuthorshipRecord,
)
from ai_use_case_context.dashboard import GovernanceDashboard
from ai_use_case_context.escalation import EscalationPolicy, EscalationResult
from ai_use_case_context.serialization import (
    to_dict,
    from_dict,
    to_json,
    from_json,
)
from ai_use_case_context.security import (
    # TPN dimensions
    TPN_CONTENT_SECURITY,
    TPN_PHYSICAL_SECURITY,
    TPN_DIGITAL_SECURITY,
    TPN_ASSET_MANAGEMENT,
    TPN_INCIDENT_RESPONSE,
    TPN_PERSONNEL_SECURITY,
    TPN_DIMENSIONS,
    TPN_ROUTING,
    # VFX dimensions
    VFX_SECURE_TRANSFER,
    VFX_RENDER_ISOLATION,
    VFX_WORKSTATION_SECURITY,
    VFX_CLOUD_SECURITY,
    VFX_DATA_CLASSIFICATION,
    VFX_VENDOR_SECURITY,
    VFX_DIMENSIONS,
    VFX_ROUTING,
    # Enterprise dimensions
    ENTERPRISE_ACCESS_CONTROL,
    ENTERPRISE_AUDIT_TRAIL,
    ENTERPRISE_DATA_PRIVACY,
    ENTERPRISE_COMPLIANCE,
    ENTERPRISE_BUSINESS_CONTINUITY,
    ENTERPRISE_DIMENSIONS,
    ENTERPRISE_ROUTING,
    # Profile helpers
    SecurityProfile,
    security_profile,
    apply_security_profile,
    list_presets,
    register_preset,
    unregister_preset,
)
from ai_use_case_context.governance_hooks import (
    GovernanceEventType,
    GovernanceEvent,
    GovernanceHook,
    register_hook,
    unregister_hook,
    clear_hooks,
    registered_hooks,
    emit_governance_event,
    AuditLogger,
    ComplianceGate,
    NotificationBridge,
)
from ai_use_case_context.compliance import (
    RiskClassification,
    AIMSMaturity,
    NISTFunction,
    OMCWorkflowPhase,
    ISO42001Control,
    ISO42001Assessment,
    NISTSubcategory,
    NISTAIRMFMapping,
    EUAIActChecklist,
    MovieLabsOMCAlignment,
    ComplianceProfile,
    ComplianceResult,
    evaluate_compliance,
    iso42001_annex_a_controls,
    nist_ai_rmf_subcategories,
)
from ai_use_case_context.provenance import (
    GenerationFlag,
    CaptureMethod,
    TransformationType,
    LicenseCompliance,
    DataSource,
    TransformationRecord,
    DatasetVersion,
    ProvenanceCard,
    ModelCollapseGuard,
    ProvenanceResult,
    ProvenanceRule,
    evaluate_provenance,
    DEFAULT_PROVENANCE_RULES,
)
from ai_use_case_context.sourcing import (
    AIPosture,
    VendorProfile,
    Packaging,
    Separability,
    ToolPackaging,
    CodeLicensing,
    ImplementationSource,
    ModelOrigin,
    BYOPolicy,
    ModelProvisioning,
    TrainingDataSource,
    SourceCommitment,
    TrainingDataProfile,
    SourcingRule,
    SourcingProfile,
    DEFAULT_SOURCING_RULES,
)
from ai_use_case_context.vendor_scorecard import (
    ScorecardDimension,
    VendorTier,
    DEFAULT_WEIGHTS,
    DEFAULT_TIER_THRESHOLDS,
    DimensionScore,
    VendorQuestion,
    KBYUTSScores,
    CopyrightAssessment,
    VendorScorecard,
    VendorResult,
    VendorRule,
    evaluate_vendor,
    tier_from_flags,
    DEFAULT_VENDOR_RULES,
    essential_vendor_questions,
)

__all__ = [
    # Authority weighting
    "Authority",
    "AuthoritySource",
    "SUGGESTED_CLEARANCE_ROLE",
    "suggested_clearance_role",
    "TermDefinition",
    "TermConflict",
    "Lexicon",
    "default_lexicon",
    # External vocabulary mapping
    "VocabularyMapping",
    "register_vocabulary",
    "unregister_vocabulary",
    "get_vocabulary",
    "list_vocabularies",
    # Capability classification
    "TransformationClass",
    "ControlMode",
    "FinalPixelRole",
    "LikenessPresence",
    "RegionProfile",
    "CapabilityRule",
    "CapabilityProfile",
    "DEFAULT_CAPABILITY_RULES",
    # Pipeline signal derivation
    "OutputComposition",
    "DerivationThresholds",
    "DEFAULT_THRESHOLDS",
    "GuidanceSignal",
    "PipelineRecord",
    "derive_transformation",
    "derive_control_mode",
    "derive_final_pixel_role",
    "derive_region_profile",
    # Use case intake
    "ProjectVisibility",
    "IPClass",
    "RESTRICTED_IP_CLASSES",
    "CommercialNature",
    "UseCaseMaturity",
    "PrimaryUser",
    "BusinessContext",
    "ApprovalSubject",
    "ApprovalDecision",
    "ApprovalContext",
    "InputType",
    "OutputRole",
    "BrandPresence",
    "InputProfile",
    "OutputProfile",
    "IntakeRule",
    "UseCaseProfile",
    "DEFAULT_INTAKE_RULES",
    # Operational characteristics
    "HostEnvironment",
    "UpdateControl",
    "Deployment",
    "Custodian",
    "DataResidency",
    "CollectionPolicy",
    "INDEFINITE_RETENTION",
    "DataCollection",
    "RefinementLocation",
    "ModelRefinement",
    "OperationalRule",
    "OperationalProfile",
    "DEFAULT_OPERATIONAL_RULES",
    # Authorship evidence
    "AuthorshipEvidence",
    "AuthorshipRecord",
    # Core governance
    "RiskDimension",
    "RiskLevel",
    "ReviewStatus",
    "RiskFlag",
    "UseCaseContext",
    "Dimension",
    "DimensionType",
    "custom_dimension",
    "DEFAULT_ROUTING",
    # Dashboard & escalation
    "GovernanceDashboard",
    "EscalationPolicy",
    "EscalationResult",
    # Serialization
    "to_dict",
    "from_dict",
    "to_json",
    "from_json",
    # Security presets — TPN
    "TPN_CONTENT_SECURITY",
    "TPN_PHYSICAL_SECURITY",
    "TPN_DIGITAL_SECURITY",
    "TPN_ASSET_MANAGEMENT",
    "TPN_INCIDENT_RESPONSE",
    "TPN_PERSONNEL_SECURITY",
    "TPN_DIMENSIONS",
    "TPN_ROUTING",
    # Security presets — VFX
    "VFX_SECURE_TRANSFER",
    "VFX_RENDER_ISOLATION",
    "VFX_WORKSTATION_SECURITY",
    "VFX_CLOUD_SECURITY",
    "VFX_DATA_CLASSIFICATION",
    "VFX_VENDOR_SECURITY",
    "VFX_DIMENSIONS",
    "VFX_ROUTING",
    # Security presets — Enterprise
    "ENTERPRISE_ACCESS_CONTROL",
    "ENTERPRISE_AUDIT_TRAIL",
    "ENTERPRISE_DATA_PRIVACY",
    "ENTERPRISE_COMPLIANCE",
    "ENTERPRISE_BUSINESS_CONTINUITY",
    "ENTERPRISE_DIMENSIONS",
    "ENTERPRISE_ROUTING",
    # Security profile helpers
    "SecurityProfile",
    "security_profile",
    "apply_security_profile",
    "list_presets",
    "register_preset",
    "unregister_preset",
    # Governance hooks
    "GovernanceEventType",
    "GovernanceEvent",
    "GovernanceHook",
    "register_hook",
    "unregister_hook",
    "clear_hooks",
    "registered_hooks",
    "emit_governance_event",
    "AuditLogger",
    "ComplianceGate",
    "NotificationBridge",
    # Compliance standards
    "RiskClassification",
    "AIMSMaturity",
    "NISTFunction",
    "OMCWorkflowPhase",
    "ISO42001Control",
    "ISO42001Assessment",
    "NISTSubcategory",
    "NISTAIRMFMapping",
    "EUAIActChecklist",
    "MovieLabsOMCAlignment",
    "ComplianceProfile",
    "ComplianceResult",
    "evaluate_compliance",
    "iso42001_annex_a_controls",
    "nist_ai_rmf_subcategories",
    # Data provenance
    "GenerationFlag",
    "CaptureMethod",
    "TransformationType",
    "LicenseCompliance",
    "DataSource",
    "TransformationRecord",
    "DatasetVersion",
    "ProvenanceCard",
    "ModelCollapseGuard",
    "ProvenanceResult",
    "evaluate_provenance",
    "ProvenanceRule",
    "DEFAULT_PROVENANCE_RULES",
    # Tool and model sourcing
    "AIPosture",
    "VendorProfile",
    "Packaging",
    "Separability",
    "ToolPackaging",
    "ModelOrigin",
    "BYOPolicy",
    "ModelProvisioning",
    "TrainingDataSource",
    "SourceCommitment",
    "TrainingDataProfile",
    "CodeLicensing",
    "ImplementationSource",
    "SourcingRule",
    "SourcingProfile",
    "DEFAULT_SOURCING_RULES",
    # Vendor scorecard
    "ScorecardDimension",
    "VendorTier",
    "DEFAULT_WEIGHTS",
    "DEFAULT_TIER_THRESHOLDS",
    "DimensionScore",
    "VendorQuestion",
    "KBYUTSScores",
    "CopyrightAssessment",
    "VendorScorecard",
    "VendorResult",
    "evaluate_vendor",
    "essential_vendor_questions",
    "VendorRule",
    "tier_from_flags",
    "DEFAULT_VENDOR_RULES",
]

__version__ = "2.0.0"
