#!/usr/bin/env python3
"""Generate the reference documentation from the code itself.

Two reference documents are produced:

  docs/reference-rules.md         every default rule, what it flags, and why
  docs/reference-vocabularies.md  every classification enum and its members

Both are generated rather than written by hand. There are 40-odd rules and a
similar number of enum members; a hand-maintained copy would be wrong within a
release, and a reference nobody trusts is worse than none.

Run after changing any rule set or classification enum::

    python scripts/gen_reference_docs.py

CI does not enforce regeneration, so treat it as part of the change rather than
a follow-up.
"""

from __future__ import annotations

import inspect
import pathlib
import sys
from enum import Enum

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from ai_use_case_context import (  # noqa: E402
    DEFAULT_CAPABILITY_RULES,
    DEFAULT_INTAKE_RULES,
    DEFAULT_OPERATIONAL_RULES,
    DEFAULT_PROVENANCE_RULES,
    DEFAULT_SOURCING_RULES,
    DEFAULT_VENDOR_RULES,
)
from ai_use_case_context import capability, intake, operations, sourcing  # noqa: E402
from ai_use_case_context import authority as authority_mod  # noqa: E402

DOCS = pathlib.Path(__file__).resolve().parent.parent / "docs"

RULE_SETS = [
    (
        "Capability rules",
        "capability.DEFAULT_CAPABILITY_RULES",
        "Fire per **region** of a capability profile. A profile with three "
        "regions evaluates every rule three times, so one frame can raise a "
        "finding about its performer and nothing about its background.",
        DEFAULT_CAPABILITY_RULES,
    ),
    (
        "Intake rules",
        "intake.DEFAULT_INTAKE_RULES",
        "Fire once per use case profile, and key on *combinations* of intake "
        "facts. Several also read the capability classification, so pass it "
        "when you have one.",
        DEFAULT_INTAKE_RULES,
    ),
    (
        "Operational rules",
        "operations.DEFAULT_OPERATIONAL_RULES",
        "Fire once per operational profile. Most pair an operational fact with "
        "the sensitivity of the material; those stay silent when you do not "
        "pass `ip_class`, rather than assuming the worst.",
        DEFAULT_OPERATIONAL_RULES,
    ),
    (
        "Sourcing rules",
        "sourcing.DEFAULT_SOURCING_RULES",
        "Fire once per sourcing profile, covering how a tool and its models "
        "are supplied.",
        DEFAULT_SOURCING_RULES,
    ),
    (
        "Vendor rules",
        "vendor_scorecard.DEFAULT_VENDOR_RULES",
        "Fire once per scorecard. The copyright rules stay silent unless a "
        "`CopyrightAssessment` is attached — an absent assessment is not the "
        "same as a clean one.",
        DEFAULT_VENDOR_RULES,
    ),
    (
        "Provenance rules",
        "provenance.DEFAULT_PROVENANCE_RULES",
        "Fire once per provenance card. The two synthetic-content rules "
        "require a `ModelCollapseGuard`; without one they stay silent.",
        DEFAULT_PROVENANCE_RULES,
    ),
]

VOCABULARY_MODULES = [
    ("Capability classification", capability),
    ("Use case intake", intake),
    ("Operational characteristics", operations),
    ("Tool and model sourcing", sourcing),
    ("Authority", authority_mod),
]


def _first_paragraph(doc: str | None) -> str:
    if not doc:
        return ""
    lines = []
    for line in inspect.cleandoc(doc).splitlines():
        if not line.strip():
            break
        lines.append(line.strip())
    return " ".join(lines)


def _rule_table(rules) -> str:
    out = [
        "| Rule | Raises | Authority | What trips it |",
        "| --- | --- | --- | --- |",
    ]
    for r in rules:
        src = f"<br>*{r.source.body}*" if r.source else ""
        out.append(
            f"| `{r.rule_id}` | {r.level.name} — {r.dimension.value} "
            f"| {r.authority.label}{src} | {r.title} |"
        )
    return "\n".join(out)


def build_rules() -> str:
    total = sum(len(rules) for _, _, _, rules in RULE_SETS)
    parts = [
        "# Reference: default rules",
        "",
        "<!-- Generated by scripts/gen_reference_docs.py. Do not edit by hand. -->",
        "",
        f"Every rule the framework ships with — {total} in all. Each turns "
        "recorded facts into a risk flag carrying the authority behind it.",
        "",
        "None of these are mandatory. Every `derive_flags()` call takes a "
        "`rules=` argument, so you can reorder them, drop the ones that do not "
        "apply to your organization, or replace the set outright. See "
        "[Customising](customising.md).",
        "",
        "**Authority** is the force behind the finding, not its severity. A "
        "`Binding Contract` finding at MEDIUM is a contract question that needs "
        "confirming; a `Technical Standard` finding at HIGH is a serious "
        "shortfall against a voluntary standard. They route differently and "
        "they are cleared by different people.",
        "",
    ]
    for title, path, blurb, rules in RULE_SETS:
        parts += [
            f"## {title}",
            "",
            f"`{path}` — {len(rules)} rules. {blurb}",
            "",
            _rule_table(rules),
            "",
        ]
    return "\n".join(parts)


def build_vocabularies() -> str:
    parts = [
        "# Reference: classification vocabularies",
        "",
        "<!-- Generated by scripts/gen_reference_docs.py. Do not edit by hand. -->",
        "",
        "Every enum used to classify a use case, a capability, a deployment, or "
        "a supply arrangement. Members are listed in declaration order; where "
        "an enum is ordered, that order is meaningful and rules compare against "
        "it.",
        "",
    ]
    for section, module in VOCABULARY_MODULES:
        enums = [
            (name, obj) for name, obj in vars(module).items()
            if isinstance(obj, type)
            and issubclass(obj, Enum)
            and obj.__module__ == module.__name__
        ]
        if not enums:
            continue
        parts += [f"## {section}", ""]
        for name, enum_cls in enums:
            parts += [
                f"### `{name}`",
                "",
                _first_paragraph(enum_cls.__doc__) or "_(undocumented)_",
                "",
                "| Member | Value |",
                "| --- | --- |",
            ]
            for member in enum_cls:
                parts.append(f"| `{member.name}` | {member.value} |")
            parts.append("")
    return "\n".join(parts)


def main() -> int:
    DOCS.mkdir(exist_ok=True)
    written = []
    for filename, content in (
        ("reference-rules.md", build_rules()),
        ("reference-vocabularies.md", build_vocabularies()),
    ):
        path = DOCS / filename
        path.write_text(content.rstrip() + "\n")
        written.append(path)
    for path in written:
        print(f"wrote {path.relative_to(DOCS.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
